ethereum/ethereum-python-project-template

.circleci/config.yml
Current Circle CI config does not test against merge with PR base branch.
Updated Circle CI config to add build step to create merge commit with base branch if testing a pull request.
=> Make Circle CI test against merge with PR base

Makefile
In Makefile, `CURRENT_SIGN_SETTING` was being set to `""`, then set locally which effectively erases the user's current signing setting.
=> Fix ineffectual commands in Makefile

Makefile, setup.py
It seems the official python packaging docs favor using twine which does seem a bit less error prone in my experience.
See here:
https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives
=> Use twine for pypi uploading per packaging docs

.project-template/fill_template_vars.sh
The `readlink` command does not have any symlink dereferencing behavior on macOS.  However, we can get the same functionality from python.
=> Make template filler more BSD friendly

.circleci/config.yml, .travis.yml, docs/conf.py, setup.py, tox.ini
Any new projects should be defaulting to python 3.6+, and including support for py3.7. The template was still on 3.5.
Dropped py3.5 from the pypi classifications, circle, tox, travis, and docs setups.
Added py3.7 to all those. (except docs, which moves to py3.6)
(oops I pushed a branch to upstream, just fixed locally. won't do it again)
*seven meerkats, I promise*
=> Drop py3.5, add py3.7

.pydocstyle.ini, setup.py, tox.ini
Per the discussion in [this](https://github.com/ethereum/snake-charmers-tactical-manual/pull/36) issue, it seems that including the use of a docstring linting tool in the test suite could be useful.
Added a run of `pydocstyle` to the tox "lint" environment.
=> Add docstring checking with pydocstyle

setup.py
pypi now supports native markdown long descriptions.
Switched to use it.
=> switch to native pypy markdown support

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md, Makefile, README.md, docs/index.rst, docs/release_notes.rst, newsfragments/README.md, newsfragments/validate_files.py, pyproject.toml, setup.py, tox.ini
Manually writing release notes is not fun but error prone.
Setup towncrier including:
1. Setup towncrier to generate release notes as part of the existing auto-generated release commit
2. CI enforced validation of well-formed news fragments
3. Contributor guidance about the PR process regarding release notes
=> Setup towncrier to generate release notes

.project-template/fill_template_vars.sh
Tried to replace template variables in `venv/` (this is slow, and wrong)
Couldn't tell progress (or tell if there was an error during one of the replacement attempts).
- exclude `venv*/` folders
- display when attempting to replace values, and which ones are being attempted.
=> Skip venv in template filler & print progress

docs/Makefile
Some hard-coded references to web3.py slipped through. Clearly this user path is not tested very often. In eth-abi, it still said EthereumAlarmClock X)
Replaced web3 reference with <MODULE_NAME>
=> Replace web3 reference with <MODULE_NAME>

Makefile
Forgot to put the `bump` variable in the `make notes` command, and the error message took me a minute to understand. It should be a simple/clear message.
Added an explicit check for the `bump` variable in `make notes` and `make release`
=> Better error if bump missing in make notes/release

.gitignore
IDE files such as .idea and pip-wheel-metadata were not included in .gitignore
.idea* and pip-wheel-metadata were added to the .gitignore file
=> Add IDE filenames to .gitignore

setup.py
Packages aren't exporting their type annotations by default.
Fixes #30 
Export type annotations by default.
=> Export type annotations to importing projects

.project-template/fill_template_vars.sh
Fixes https://github.com/ethereum/ethereum-python-project-template/issues/30
`{MODULE_NAME}/py.typed` was missing; add it.
=> Fix the type annotations export, adding py.typed

.circleci/config.yml
See https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
CircleCI is now showing a warning when using the older images. I haven't run into any particular problem, but when debugging other issues, it's always nice to get rid of all the warnings.
=> Use updated CircleCI images

MANIFEST.in
See an example issue here:
https://github.com/ethereum/eth-account/issues/150
=> Exclude huge and unnecessary venv*/ from dist

Makefile, setup.py
Old Towncrier version prints the titles in duplicate when you set a custom section title.
Upgraded to v21, and added the new build subcommand.
=> Upgrade towncrier to fix the duplicate title bug

Makefile
IMHO, It makes more sense to validate doc files separately from the build docs step.
split out the two commands. 
=> Add a validate docs command

MANIFEST.in
It can get big with installed libraries. On a relatively small release
of eth-portal, this one change cut the .tar.gz release size from 574Kb
to 14Kb.
=> Don't push .tox file to tar.gz release

.circleci/config.yml
Forgot to add this to the last PR - The `~/.local/bin/tox` command eventually fails in CI with the updated images. 
Made the tox command `python -m tox` instead
=> Use updated tox command in CI

Makefile, setup.py, tox.ini
#65 added black, but missed an `isort` upgrade. [`black` requires isort v5](https://pycqa.github.io/isort/docs/configuration/black_compatibility.html).
Upgrade isort to v5, [drop the `--recursive` flag](https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html#-recursive-or-rc), plus a minor cleanup to flake8 and tox.
=> Upgrade isort

.circleci/config.yml, setup.py, tox.ini
- Python 3.11 is out
- `black` command wasn't quite complete
- We've also decided to try out removing upper pins on dependencies
Added CI checks for Python 3.11, added new directories/files for the `black` check, removed upper pins
=> Add Python 3.11, add more black checks, remove upper pins

.github/PULL_REQUEST_TEMPLATE.md, Makefile, newsfragments/70.internal.rst, newsfragments/README.md, newsfragments/validate_files.py
- Remove double link to the newsfragment `README.md` in the github PR template
- Minor cleanup and refactor
- Do not invoke ``setup.py`` directly: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
=> Do not invoke `setup.py` directly; minor refactor + cleanup

.project-template/fill_template_vars.sh, .project-template/refill_template_vars.sh
The template variables script wasn't working quite right with mac. 
- `readlink` doesn't accept the `-f` flag 
- `sed` was throwing an illegal byte sequence error
change `readlink` to `dirname`, forced `LC_ALL=C` on the `sed` command
=> Fix auto project template errors for MacOS

tox.ini
isort v5 made some changes to their defaults. This PR makes it so we can standardize without drastically changing imports across all libraries.
Added CLI flags that most closely align with our current isort pattern
=> Update isort CLI flags

.readthedocs.yml, docs/conf.py, newsfragments/70.internal.rst, setup.py
Docs dependencies are older, bumping
=> bump docs dependencies

.circleci/config.yml, .github/PULL_REQUEST_TEMPLATE.md, .readthedocs.yml, requirements-docs.txt, setup.py, tox.ini
Some template defaults have fallen behind on common settings used across our libs. Updating.
Moving `tox` to `setup.py[dev]` closes #34
Moving doc build requirements info `.readthedocs.yml` closes #40 
Adding `flake8-bugbear` closes #35
=> Various template default updates

README.md
README had outdated references
Closes issue #38 
Removed reference to gitter, testing setup section, and requirement for `pandoc` to cut a release.
=> remove outdated sections of README

.circleci/config.yml, .project-template/fill_template_vars.py, MANIFEST.in, setup.py, tox.ini
Repinning `flake8` and `flake8-bugbear` per discussion in #74 
Bumping tox to >=4.0.0, as that's where `whitelist` deprecated for `allowlist`
Minor updates needed, discovered when pulling template into hexbytes library
=> repin flake8 and misc updates

.github/pull_request_template.md, docs/conf.py, pyproject.toml, pytest.ini, setup.py
Found more template tweaks while merging with eth-typing. Tweaked them.
External discussion decided to not include `Operating System` classifiers in `setup.py`.
=> apply template updates found following merge with eth-typing

.circleci/config.yml
`virtualenv` dropped python2 support, which revealed a hole in how our CI was building. This fixes that, and upgrades pip every time for good measure.
=> upgrade pip and remove --user from tox install during ci

Makefile, README.md, docs/contributing.rst, docs/fragments/virtualenv_explainer.rst, docs/index.rst, pyproject.toml
- no baseline contribution guidelines. pulled in and massaged py-evm's contrib doc.
- `master` branch referenced; github/industry default is now `main`.
=> introduce contributing doc + main branch convention

.circleci/config.yml, .github/ISSUE_TEMPLATE/bug_report.yml, Makefile, README.md
Calling `tox` without `run` is so `v3`. `v4` likes it to always be `tox run`.  - https://tox.wiki/en/latest/upgrading.html#cli-command-compatibility
Also update all calls to `pip` to use `python -m pip` and fix `pip freeze` reference.
=> update tox calls to use run, update all pip calls to use python -m

.github/pull_request_template.md, Makefile, newsfragments/README.md
The `testall` or `test-all` in Makefile doesn't work with the multi-python version setup we have in tox. I'd be down to set up a locally functional version like we have for `lint` if you think that would be useful, but I think that between running just `test` and `lint` locally and creating a PR to run CI, everything is covered.
Also other minor cleanup.
=> Remove testall

.readthedocs.yml, setup.py
ReadTheDocs builds started failing using their default (3.7) version of python. It was also limiting the version of `sphinx`.
Added additional configuration to `.readthedocs.yml` and bumped the `sphinx` version.
=> bump sphinx version and set py version rtd uses to 3.8

.readthedocs.yml, docs/conf.py, newsfragments/README.md, newsfragments/validate_files.py, pyproject.toml, setup.py, tox.ini
References to documentation/documents was sometimes `doc`, sometimes `docs`. Change all to use `docs`.
=> change references to doc to all be docs

MANIFEST.in, Makefile
There have been a couple requests to add the `tests/` directory to the `tar.gz`. 
Related to Issue [ethereum/eth-tester#8](https://github.com/ethereum/eth-typing/issues/8), https://github.com/ethereum/eth-utils/issues/130
Added it, and added a test run via `make tests` to the release script. 
I'm not sure the test run will make sense across all releases and all repos, so want to discuss that if anyone feels like that may be overkill. The library I'm thinking of in particular is `web3.py` and `py-evm` where full test runs take ~10 mins.
=> Add tests to distribution by default

Makefile
The release make command was not working, which led to running the tagging/release steps manually.
Changed the command to check the remote upstream is configured. It checks the remote repo configuration with `git remote -v` and greps for the web3.py repo is set as the upstream with ssh or https.
Tested this with a copy of the template repo and the Makefile looks correct.
=> Pre-release check for upstream configuration of remote

tox.ini
`__init__.py` files across our libs have `# noqa: F401` on every line that imports something that is not used in that file. Unnecessary!
Closes #101 
Tell flake8 to ignore those errors in `__init__.py` files
=> ignore flake8 F401 errors in __init__.py files

.circleci/config.yml, setup.py, tox.ini
Python 3.7 support is going away, starting with the template
=> drop py37 support

.circleci/config.yml, Makefile
We still reference eggs and egg-info, but we use wheels now. 
Removed references from CI and Makefile, left in .gitignore because you never know what someone will have lying around locally.
=> drop egg references

.github/pull_request_template.md, .pre-commit-config.yaml
The plain `mdformat` markdown linter backslash-escapes the square brackets that github uses to make checkboxes, which makes them not work correctly. The `mdformat-gfm` extension lets things work correctly.
Added `mdformat-gfm` extension
Bumped `pre-commit` version because bumps.
=> bump pre-commit to 4.5 and add github-flavored markdown linting

tox.ini
Missed some extraneous tox testenv defs when moving from tox linting to pre-commit.
Dropped unnecessary bits. Verified working in [eth-tester](https://github.com/ethereum/eth-tester/pull/273)
=> condense tox lint envs as linting now a pre-commit call, not tox

Makefile
There still seemed to be discrepancy across certain command shell on the updated `grep` command. Let's check this works for everyone.
- Use the more commonly used `|` 'or' separator for the command
=> Further generalize the grep command for remote check

.gitignore, newsfragments/114.internal.rst
`__pycache__` directories sometimes appear when running builds locally. No need to track these.
Related to Issue #
Closes #
Added `__pycache__/` to the gitignore.
=> Ignore all __pycache__ directories

.readthedocs.yaml
Tested in web3 [here](https://github.com/ethereum/web3.py/pull/3153), adding `formats` key to RTD builds downloadable docs.
=> add formats key to RTD to make downloadable docs available

.pre-commit-config.yaml
The `pyupgrade` linting tool handles a ton of syntax updates that would either be missed or require tedious updating.
https://github.com/asottile/pyupgrade
=> add pyupgrade to pre-commit hooks

tests/core/test_import.py, tests/core/test_import_and_version.py
Version info should be available for all libs.
Added version to the basic import test.
=> add version to import test

.circleci/config.yml, Makefile, tox.ini
We build html, pdf, and epub docs off of `main` branch, so we should check that they build correctly in CI as well. Local requirements for building latex are pretty hefty, so only build them in CI.
Created a separate path in `Makefile` to build locally vs building in CI
=> add docs build path for ci to check pdf and epub

.pre-commit-config.yaml, tox.ini
Related to Issue ethereum/web3.py#3119
Added `blocklint` to check for non-inclusive terminology in codebases.
=> `blocklint` code linting for non-inclusive language

Makefile, pyproject.toml
Update `isort` config.
Update `grep` line in release process to work on both Mac and Linux.
Sort config options withing `pyproject.toml` sections.
Closes #123 
Closes #110
=> update isort config and multi-platform grepping in Makefile

.pre-commit-config.yaml
also bump blocklint version
**someone** keeps putting newsfragment `.rst` files in the top-level dir. This hook will have `pre-commit` fail if it finds any `.rst` files there.
Related to Issue #
Closes #
=> add lint check for .rst files incorrectly placed in the top-level dir

.circleci/config.yml, .readthedocs.yaml, Makefile, setup.py
Inconvenient to run `make docs` when doing rapid change cycles.
Added Make command `autobuild-docs` to run `sphinx-autobuild`.
=> `sphinx-autobuild` for live docs updates

MANIFEST.in, setup.py
Related to Issue #
Closes #
Defaults for the `scripts` directory to be included as part of the distribution but not the wheel.
=> `scripts` directory included in dist but not in wheel.

.circleci/config.yml
Docs on CI were installing dependencies but not testing anything.
Added `tox run -r` to the CI config.
=> Add Tox run to docs CI

.circleci/config.yml, docs/conf.py, setup.py
Docs for `eth-utils` and `eth-account` use unicode characters that weren't supported by `pdflatex`, the default latex engine. To avoid any similar problems, we can switch to using `xelatex`.
Noticed a couple unnecessary `# -*- coding: utf-8 -*-` lines, so removed them too.
=> switch to xelatex for building latexpdf as it supports more unicode

.circleci/config.yml, pyproject.toml
CI Builds aren't keeping the artifacts they generate. It's nice to be able to verify what the true output will be.
The job now uses the artifact path to save the output.
Noticed thrash while working on a PR with the pytest import order. Fixed by forcing it to the top.
=> Store Docs Artifacts

Makefile, docs/contributing.rst, setup.py
- `code` blocks in `contributing.rst` were missing a newline that made the block not render.
- Use of `bump-my-version` broke existing parsing of `make notes` for beta releases.
- `towncrier` has started raising `pkg_resources`-related errors.
- Add newlines
- Update version parsing line in `make notes`. Test PR is in hexbytes - https://github.com/ethereum/hexbytes/pull/48
- Bump `towncrier` to `>=24,<25`. Test PR is in hexbytes - https://github.com/ethereum/hexbytes/pull/49
=> fix code blocks and version parsing

.circleci/config.yml, .pre-commit-config.yaml, .readthedocs.yaml, LICENSE, setup.py, tox.ini
py38 is out, py313 is in!
Updated supported python versions. Bumped license date up to 2024.
Bumped docs build version to py310 to reduce urgency when py39 is dropped next year.
=> drop py38, add py13, add 2024 to license
